name: progress_dialog_null_safe
description: Reviving an old progress dialog
version: 1.0.7
homepage: https://github.com/CodingFries/progress_dialog

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/